export default {
    // 主题色修改
    THEME_CHANGE: 'THEME_CHANGE',

    // 最热模块加载
    POPULAR_REFRESH: 'POPULAR_REFRESH',
    POPULAR_REFRESH_SUCCESS: 'POPULAR_REFRESH_SUCCESS',
    POPULAR_REFRESH_FAIL: 'POPULAR_REFRESH_FAIL',
}
